#! /bin/bash

# ------------------------------------------------------------------------
# USAGE 
# ------------------------------------------------------------------------

usage(){
    echo 
    echo "usage: $(basename $0) [-u] "
    echo "    -u    update only"
    echo "    -h    help"
    echo
}


while [[ "$#" > 0 ]]; do 
    case $1 in
        -u) UPDATE="1";shift;;
        -*) usage;exit;;
        *) break;;
    esac
done



# ------------------------------------------------------------------------
# DEFINES
# ------------------------------------------------------------------------

CSOPT=""
SRC_DIR=$PAN_BUILD_DIR/src
lockdir=$SRC_DIR/.$(basename $0).lock



# ------------------------------------------------------------------------
# CHECK CONDITIONS
# ------------------------------------------------------------------------

if [[ -z "$PAN_BUILD_DIR" ]]; then
    echo 
    echo "PAN_BUILD_DIR must be defined"
    echo
    exit
fi


if [[ ! -d "$SRC_DIR" ]]; then
    echo 
    echo "$SRC_DIR not found"
    echo
    exit
fi


if mkdir "$lockdir"
then
    echo >&2 "successfully acquired lock"

    # Remove lockdir when the script finishes, or when it receives a signal
    trap 'rm -rf "$lockdir"' 0    # remove directory when script finishes
else
    echo >&2 "cannot acquire lock, giving up on $lockdir"
    exit 0
fi





# ------------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------------

if [[ -z "$UPDATE" ]]; then
    # only run find when not updating
    find $SRC_DIR/apps \
        $SRC_DIR/libs \
        $SRC_DIR/sys \
        $SRC_DIR/mgmt \
        -path $SRC_DIR/apps/python* -prune -o \
        -path $SRC_DIR/apps/perl* -prune -o \
        -path $SRC_DIR/libs/python* -prune -o \
        -path $SRC_DIR/libs/cavium* -prune -o \
        -regex ".*\.[ch]\(pp\)?" \
        -type f \
        -print > $SRC_DIR/cscope.files
fi


cd $SRC_DIR
cscope -icscope.files -ubqk $CSOPT -fcscope.out


