#! /bin/bash

# 
# deletes an entry from ~/.ssh/known_hosts file
#

function usage(){
    echo "Usage:"
    echo "  rmssh <ip-address>"
    echo "  rmssh user@<ip-address>"
    echo 
}


if [ $# -lt 1 ]; then
    usage
    exit 1
fi

# remove user@ from the front if present
IP=${1#*@}
HOSTS_FILE=~/.ssh/known_hosts

if [ -e $HOSTS_FILE ]; then
    sed -i.rmssh "/^$IP/d" $HOSTS_FILE
    rm $HOSTS_FILE.rmssh
fi


